version: '3'
services:
  db:
     image: postgres
     restart: always
     volumes:
       - ./data/db:/var/lib/postgrersql/data
     ports:
       - 5432:5432

     environment:
      - POSTGRES_DB=TESTdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080